### ISSUE TITLE
Bug lors de scan d'un autre CIDR 

### ISSUE THREAD

**Issue by 1ntegrxl** [darcosion/Echosounder#56]
Cette fonction de scan repose sur le scan ARP, donc il n'est pas possible de faire un scan sur une interface autre que l'interface locale. 

https://github.com/darcosion/Echosounder/blob/b12f9a9e2eb651654ca5f4af672ecf6b7399ff91/echosounder.py#L139-L156 

Voici une capture d'écran illustrant le soucis avec un scan du réseau HTB : 
![ploup](https://user-images.githubusercontent.com/56651736/158986240-9516618b-38e1-410c-ac40-92cb00cbbf67.png)

**Comment by darcosion** [comment]
Le refacto n'a pas suffit. les fonctionnalités de scan rap & fast_ping sont contiennent du code legacy qui n'a pas du tout la bonne vision.

Actuellement, l'issue #66 serait plus à surveiller car ces fonctions vont être séparés du reste dans #75 et pourront peut-être faire disparaître ce bug en prise en charge d'interface.

**Comment by darcosion** [comment]
Cette issue peut être fermée car #75  résous techniquement son problème.  
En effet, la séparation entre scan locaux/distants permet d'éviter un scan ARP distant.

Néanmoins, il faudra surveiller à l'avenir l'emploi d'interface par les scan locaux car ils ne se fient pas à l'adressage IP mais à leur interface de référence, comme mentionné ici https://github.com/darcosion/Echosounder/issues/75#issuecomment-1113988481.
